FROM node:lts-alpine

RUN apk add --no-cache bash

WORKDIR /home/node/app

COPY ./package.json /home/node/app/

EXPOSE 5000

RUN npm i && \
    npm run build &&

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD node healthcheck.js

COPY . .

CMD [ "npm", "start" ]