version: '3'

services:
  app:
    container_name: planing-poker-jira
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app