version: '3'

services:
  app:
    container_name: planing-poker-jira
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
