FROM node:lts-alpine

RUN apk add --no-cache bash

WORKDIR /home/node/

COPY . /home/node/

EXPOSE 8080

RUN npm i

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD node healthcheck.js

COPY . .

CMD [ "npm", "run", "start:dev" ]